# Generated by Django 3.0.5 on 2020-04-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=125.0),
            preserve_default=False,
        ),
    ]
