# Generated by Django 3.0.5 on 2020-05-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200512_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(blank=True, choices=[('ND', 'New Delhi'), ('UP', 'Uttar Pradesh'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('GJ', 'Gujrat'), ('AP', 'Arunachal Pradesh')], max_length=3),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment_info',
            field=models.CharField(choices=[('UPI', 'UPI'), ('NB', 'Net Banking'), ('CDC', 'Credit/Debit Card')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(choices=[('ND', 'New Delhi'), ('UP', 'Uttar Pradesh'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('GJ', 'Gujrat'), ('AP', 'Arunachal Pradesh')], max_length=3),
        ),
    ]
