# Generated by Django 3.0.5 on 2020-05-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200429_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
